import * as Y from 'yjs';
import { Awareness, encodeAwarenessUpdate, applyAwarenessUpdate } from 'y-protocols/awareness';
import Peer from '@thaunknown/simple-peer';
import { get, set } from 'idb-keyval';
import {
	decrypt,
	encrypt,
	fromBase64Url,
	importKey,
	sign,
	toBase64Url,
	verify,
	type ShareLink
} from './crypto';

/**
 * Peer-to-peer sync for a shared note.
 *
 * The server is a signaling gateway only: it introduces peers and relays
 * connection handshakes. Note content travels browser-to-browser over WebRTC
 * and never passes through it.
 *
 * ## Why a signed update log rather than Yjs's normal sync
 *
 * Yjs's sync protocol computes a diff from a peer's state vector, so the bytes
 * on the wire are freshly generated by whoever answers. Those bytes can't carry
 * a meaningful signature — the sender would have to mint one, which is exactly
 * what a viewer must not be able to do.
 *
 * So updates are exchanged as an append-only log of *signed blobs*. A signature
 * covers the update bytes, so any peer can relay a blob verbatim and every peer
 * verifies it independently. That buys two things at once: view-only is
 * cryptographically real, and viewers can still serve the document to each
 * other, because relaying is not authoring.
 */

export type Role = 'editor' | 'viewer';
export type ProviderStatus = 'connecting' | 'waiting' | 'connected';

type LogEntry = {
	id: string;
	/** base64url update bytes */
	u: string;
	/** base64url Ed25519 signature over those bytes */
	s: string;
	/** Full-state snapshot, used to bound log growth. */
	snap?: boolean;
};

type Frame =
	| { t: 'have'; ids: string[] }
	| { t: 'want'; ids: string[] }
	| { t: 'entries'; entries: LogEntry[] }
	| { t: 'aware'; u: string };

/** Beyond this, an editor collapses the log into one snapshot entry. */
const SNAPSHOT_AFTER = 100;
/** Non-snapshot entries a peer retains. Older history is covered by snapshots. */
const KEEP_ENTRIES = 400;

const logKey = (docId: string) => `note-speak:sharelog:${docId}`;

export class SignedDocProvider {
	readonly doc: Y.Doc;
	readonly awareness: Awareness;
	readonly role: Role;

	status: ProviderStatus = 'connecting';
	peerCount = 0;
	onstatus: (() => void) | null = null;

	#link: ShareLink;
	#key: CryptoKey | null = null;
	#socket: WebSocket | null = null;
	#peers = new Map<string, Peer.Instance>();
	#log = new Map<string, LogEntry>();
	#selfId = toBase64Url(crypto.getRandomValues(new Uint8Array(8)));
	#destroyed = false;
	#retry = 0;
	#retryTimer: ReturnType<typeof setTimeout> | undefined;
	#saveTimer: ReturnType<typeof setTimeout> | undefined;

	constructor(link: ShareLink, doc: Y.Doc) {
		this.#link = link;
		this.doc = doc;
		this.role = link.signSeed ? 'editor' : 'viewer';
		this.awareness = new Awareness(doc);
	}

	async connect(signalingUrl: string) {
		this.#key = await importKey(this.#link.symKey);
		await this.#loadLog();

		this.doc.on('update', this.#onLocalUpdate);
		this.awareness.on('update', this.#onAwarenessUpdate);
		this.#openSocket(signalingUrl);
	}

	destroy() {
		this.#destroyed = true;
		clearTimeout(this.#retryTimer);
		clearTimeout(this.#saveTimer);
		this.doc.off('update', this.#onLocalUpdate);
		this.awareness.off('update', this.#onAwarenessUpdate);
		for (const peer of this.#peers.values()) peer.destroy();
		this.#peers.clear();
		this.#socket?.close();
		this.#socket = null;
		void this.#saveLog();
	}

	// ---- log ----

	async #loadLog() {
		const stored = await get<LogEntry[]>(logKey(this.#link.docId));
		if (!stored?.length) return;
		for (const entry of stored) {
			// Re-verify on load: storage is not a trust boundary, and a log written
			// by an older link must not be replayed under a rotated key.
			if (await verify(this.#link.signPub, fromBase64Url(entry.u), entry.s)) {
				this.#log.set(entry.id, entry);
				Y.applyUpdate(this.doc, fromBase64Url(entry.u), 'remote');
			}
		}
	}

	#queueSave() {
		clearTimeout(this.#saveTimer);
		this.#saveTimer = setTimeout(() => void this.#saveLog(), 500);
	}

	async #saveLog() {
		const entries = [...this.#log.values()];
		const snapshots = entries.filter((e) => e.snap);
		const regular = entries.filter((e) => !e.snap).slice(-KEEP_ENTRIES);
		await set(logKey(this.#link.docId), [...snapshots, ...regular]);
	}

	#onLocalUpdate = (update: Uint8Array, origin: unknown) => {
		// Remote updates are already in the log; re-signing them would fork history.
		if (origin === 'remote' || this.role !== 'editor' || !this.#link.signSeed) return;
		void this.#appendSigned(update, false);
	};

	async #appendSigned(update: Uint8Array, snap: boolean) {
		const seed = this.#link.signSeed;
		if (!seed) return;
		const entry: LogEntry = {
			id: toBase64Url(crypto.getRandomValues(new Uint8Array(12))),
			u: toBase64Url(update),
			s: await sign(seed, update),
			...(snap ? { snap: true } : {})
		};
		this.#log.set(entry.id, entry);
		this.#broadcast({ t: 'entries', entries: [entry] });
		this.#queueSave();
		if (!snap && this.#log.size > SNAPSHOT_AFTER) await this.#compact();
	}

	/**
	 * Collapse history into one signed snapshot.
	 *
	 * Only an editor can do this, because a snapshot is an authored update. Peers
	 * without the key keep appending until an editor next compacts — bounded by
	 * KEEP_ENTRIES on disk, so the log cannot grow without limit either way.
	 */
	async #compact() {
		const seed = this.#link.signSeed;
		if (!seed) return;
		const state = Y.encodeStateAsUpdate(this.doc);
		const entry: LogEntry = {
			id: toBase64Url(crypto.getRandomValues(new Uint8Array(12))),
			u: toBase64Url(state),
			s: await sign(seed, state),
			snap: true
		};
		this.#log.clear();
		this.#log.set(entry.id, entry);
		this.#broadcast({ t: 'entries', entries: [entry] });
		this.#queueSave();
	}

	// ---- signaling ----

	#openSocket(url: string) {
		if (this.#destroyed) return;
		const socket = new WebSocket(url);
		this.#socket = socket;

		socket.onopen = () => {
			this.#retry = 0;
			socket.send(
				JSON.stringify({ type: 'subscribe', topic: this.#link.docId, from: this.#selfId })
			);
			socket.send(
				JSON.stringify({ type: 'announce', topic: this.#link.docId, from: this.#selfId })
			);
			this.#setStatus(this.#peers.size ? 'connected' : 'waiting');
		};

		socket.onmessage = (event) => void this.#onSignal(event);

		socket.onclose = () => {
			if (this.#destroyed) return;
			this.#setStatus('connecting');
			// Exponential backoff, capped — a dropped gateway must not become a
			// reconnect storm across every open tab.
			const delay = Math.min(30_000, 500 * 2 ** this.#retry++);
			this.#retryTimer = setTimeout(() => this.#openSocket(url), delay);
		};

		socket.onerror = () => socket.close();
	}

	async #onSignal(event: MessageEvent) {
		let message: { type: string; from?: string; to?: string; signal?: unknown };
		try {
			message = JSON.parse(typeof event.data === 'string' ? event.data : '');
		} catch {
			return;
		}
		const from = message.from;
		if (!from || from === this.#selfId) return;

		if (message.type === 'announce') {
			// Deterministic initiator so two peers never both dial: lower id calls.
			if (!this.#peers.has(from)) this.#createPeer(from, this.#selfId < from);
			// Answer so the newcomer learns about peers that were already here.
			this.#socket?.send(
				JSON.stringify({
					type: 'announce-ack',
					topic: this.#link.docId,
					from: this.#selfId,
					to: from
				})
			);
		} else if (message.type === 'announce-ack' && message.to === this.#selfId) {
			if (!this.#peers.has(from)) this.#createPeer(from, this.#selfId < from);
		} else if (message.type === 'signal' && message.to === this.#selfId) {
			const peer = this.#peers.get(from) ?? this.#createPeer(from, false);
			try {
				peer.signal(message.signal as Peer.SignalData);
			} catch {
				/* malformed signal from a stale peer */
			}
		} else if (message.type === 'leave') {
			this.#peers.get(from)?.destroy();
			this.#peers.delete(from);
			this.#updatePeerCount();
		}
	}

	#createPeer(remoteId: string, initiator: boolean): Peer.Instance {
		const peer = new Peer({ initiator, trickle: true });
		this.#peers.set(remoteId, peer);

		peer.on('signal', (signal) => {
			this.#socket?.send(
				JSON.stringify({
					type: 'signal',
					topic: this.#link.docId,
					from: this.#selfId,
					to: remoteId,
					signal
				})
			);
		});
		peer.on('connect', () => {
			this.#updatePeerCount();
			void this.#send(peer, { t: 'have', ids: [...this.#log.keys()] });
			const local = this.awareness.getLocalState();
			if (local) {
				void this.#send(peer, {
					t: 'aware',
					u: toBase64Url(encodeAwarenessUpdate(this.awareness, [this.doc.clientID]))
				});
			}
		});
		peer.on('data', (data: Uint8Array) => void this.#onData(data, peer));
		peer.on('close', () => {
			this.#peers.delete(remoteId);
			this.#updatePeerCount();
		});
		peer.on('error', () => {
			this.#peers.delete(remoteId);
			this.#updatePeerCount();
		});
		return peer;
	}

	// ---- framing ----

	async #send(peer: Peer.Instance, frame: Frame) {
		if (!this.#key || !peer.connected) return;
		const bytes = new TextEncoder().encode(JSON.stringify(frame));
		try {
			peer.send(await encrypt(this.#key, bytes));
		} catch {
			/* channel closed mid-send */
		}
	}

	#broadcast(frame: Frame) {
		for (const peer of this.#peers.values()) void this.#send(peer, frame);
	}

	async #onData(data: Uint8Array, from: Peer.Instance) {
		if (!this.#key) return;
		const plain = await decrypt(this.#key, new Uint8Array(data));
		// A frame we cannot decrypt came from someone without the content key.
		// Drop it silently; there is nothing useful to tell the user.
		if (!plain) return;

		let frame: Frame;
		try {
			frame = JSON.parse(new TextDecoder().decode(plain));
		} catch {
			return;
		}

		if (frame.t === 'have') {
			const theirs = new Set(frame.ids);
			const missing = frame.ids.filter((id) => !this.#log.has(id));
			const offer = [...this.#log.values()].filter((entry) => !theirs.has(entry.id));
			if (missing.length) void this.#send(from, { t: 'want', ids: missing });
			if (offer.length) void this.#send(from, { t: 'entries', entries: offer });
		} else if (frame.t === 'want') {
			const wanted = frame.ids
				.map((id) => this.#log.get(id))
				.filter((entry): entry is LogEntry => !!entry);
			if (wanted.length) void this.#send(from, { t: 'entries', entries: wanted });
		} else if (frame.t === 'entries') {
			await this.#applyEntries(frame.entries);
		} else if (frame.t === 'aware') {
			// Presence is deliberately unsigned: a viewer must be able to show a
			// cursor without holding a key that would also let them edit.
			applyAwarenessUpdate(this.awareness, fromBase64Url(frame.u), 'remote');
		}
	}

	async #applyEntries(entries: LogEntry[]) {
		let applied = 0;
		for (const entry of entries) {
			if (this.#log.has(entry.id)) continue;
			const update = fromBase64Url(entry.u);
			// The security boundary. An unsigned or wrongly-signed update is dropped
			// here, in every peer, which is why a view-only link cannot write.
			if (!(await verify(this.#link.signPub, update, entry.s))) continue;
			this.#log.set(entry.id, entry);
			Y.applyUpdate(this.doc, update, 'remote');
			applied++;
		}
		if (applied) {
			this.#queueSave();
			// Relay onward so a peer that joined late is reachable through anyone.
			this.#broadcast({ t: 'entries', entries });
		}
	}

	#onAwarenessUpdate = (
		{ added, updated, removed }: { added: number[]; updated: number[]; removed: number[] },
		origin: unknown
	) => {
		if (origin === 'remote') return;
		const changed = [...added, ...updated, ...removed];
		this.#broadcast({ t: 'aware', u: toBase64Url(encodeAwarenessUpdate(this.awareness, changed)) });
	};

	#updatePeerCount() {
		this.peerCount = [...this.#peers.values()].filter((p) => p.connected).length;
		this.#setStatus(this.peerCount > 0 ? 'connected' : 'waiting');
	}

	#setStatus(status: ProviderStatus) {
		if (this.status === status) return;
		this.status = status;
		this.onstatus?.();
	}
}
