import * as Y from 'yjs';
import { Awareness, encodeAwarenessUpdate, applyAwarenessUpdate } from 'y-protocols/awareness';
import Peer from '@thaunknown/simple-peer';
import { get, set } from 'idb-keyval';
import {
	decrypt,
	encrypt,
	fromBase64Url,
	importKey,
	sign,
	toBase64Url,
	verify,
	type ShareLink
} from './crypto';

/**
 * Peer-to-peer sync for a shared note.
 *
 * The server is a signaling gateway only: it introduces peers and relays
 * connection handshakes. Note content travels browser-to-browser over WebRTC
 * and never passes through it.
 *
 * ## Why a signed update log rather than Yjs's normal sync
 *
 * Yjs's sync protocol computes a diff from a peer's state vector, so the bytes
 * on the wire are freshly generated by whoever answers. Those bytes can't carry
 * a meaningful signature — the sender would have to mint one, which is exactly
 * what a viewer must not be able to do.
 *
 * So updates are exchanged as an append-only log of *signed blobs*. A signature
 * covers the update bytes, so any peer can relay a blob verbatim and every peer
 * verifies it independently. That buys two things at once: view-only is
 * cryptographically real, and viewers can still serve the document to each
 * other, because relaying is not authoring.
 */

export type Role = 'editor' | 'viewer';
export type ProviderStatus = 'connecting' | 'waiting' | 'connected';

type LogEntry = {
	id: string;
	/** base64url update bytes */
	u: string;
	/** base64url Ed25519 signature over those bytes */
	s: string;
	/** Full-state snapshot, used to bound log growth. */
	snap?: boolean;
};

type Frame =
	| { t: 'have'; ids: string[] }
	| { t: 'want'; ids: string[] }
	| { t: 'entries'; entries: LogEntry[] }
	| { t: 'aware'; u: string };

/**
 * Wire framing.
 *
 * A WebRTC data channel refuses messages beyond its `maxMessageSize` — 64 KB is
 * the interoperable floor — and `simple-peer` does no chunking of its own. That
 * was invisible while notes were text, and broke the moment a note could carry
 * an embedded image: the update simply never arrived, with no error anywhere.
 *
 * Every frame therefore carries a one-byte kind:
 *
 *   whole: [0x00][ciphertext…]
 *   chunk: [0x01][msgId:4][seq:2][total:2][ciphertext slice…]
 *
 * Chunking happens *after* encryption, so the wire format stays opaque and a
 * relay learns nothing from message boundaries.
 */
const KIND_WHOLE = 0x00;
const KIND_CHUNK = 0x01;
const CHUNK_HEADER = 9;
const CHUNK_PAYLOAD = 48 * 1024;
/** Bounds a peer's claimed message size: 512 × 48 KB ≈ 24 MB. */
const MAX_CHUNKS = 512;
/** Partial messages are abandoned if the rest never arrives. */
const REASSEMBLY_TIMEOUT_MS = 60_000;

type Partial = { chunks: (Uint8Array | undefined)[]; received: number; total: number; at: number };

/** Beyond this, an editor collapses the log into one snapshot entry. */
const SNAPSHOT_AFTER = 100;
/** Non-snapshot entries a peer retains. Older history is covered by snapshots. */
const KEEP_ENTRIES = 400;
/**
 * Byte budget, enforced alongside the entry counts.
 *
 * Counting entries alone was fine while an update was a few hundred bytes. With
 * an embedded image a single entry can be half a megabyte, so 400 of them is
 * hundreds of megabytes sitting in IndexedDB — a quota failure rather than a
 * cache. Whichever limit trips first wins.
 */
const SNAPSHOT_AFTER_BYTES = 2 * 1024 * 1024;
const KEEP_BYTES = 8 * 1024 * 1024;

const entryBytes = (entry: LogEntry) => entry.u.length + entry.s.length;

const logKey = (docId: string) => `note-speak:sharelog:${docId}`;

export class SignedDocProvider {
	readonly doc: Y.Doc;
	readonly awareness: Awareness;
	readonly role: Role;

	status: ProviderStatus = 'connecting';
	peerCount = 0;
	onstatus: (() => void) | null = null;
	/**
	 * Surfaced to the user. Silence is the wrong default here: an update that is
	 * dropped rather than sent leaves two peers quietly disagreeing about the
	 * note, which is worse than an error.
	 */
	onerror: ((message: string) => void) | null = null;

	#link: ShareLink;
	#key: CryptoKey | null = null;
	#socket: WebSocket | null = null;
	#peers = new Map<string, Peer.Instance>();
	#log = new Map<string, LogEntry>();
	/** In-flight chunked messages, per peer, so a disconnect drops its partials. */
	#partials = new Map<Peer.Instance, Map<number, Partial>>();
	#selfId = toBase64Url(crypto.getRandomValues(new Uint8Array(8)));
	#destroyed = false;
	#retry = 0;
	#retryTimer: ReturnType<typeof setTimeout> | undefined;
	#saveTimer: ReturnType<typeof setTimeout> | undefined;

	constructor(link: ShareLink, doc: Y.Doc) {
		this.#link = link;
		this.doc = doc;
		this.role = link.signSeed ? 'editor' : 'viewer';
		this.awareness = new Awareness(doc);
	}

	async connect(signalingUrl: string) {
		this.#key = await importKey(this.#link.symKey);
		await this.#loadLog();

		this.doc.on('update', this.#onLocalUpdate);
		this.awareness.on('update', this.#onAwarenessUpdate);
		this.#openSocket(signalingUrl);
	}

	destroy() {
		this.#destroyed = true;
		clearTimeout(this.#retryTimer);
		clearTimeout(this.#saveTimer);
		this.doc.off('update', this.#onLocalUpdate);
		this.awareness.off('update', this.#onAwarenessUpdate);
		for (const peer of this.#peers.values()) peer.destroy();
		this.#peers.clear();
		this.#partials.clear();
		this.#socket?.close();
		this.#socket = null;
		void this.#saveLog();
	}

	// ---- log ----

	async #loadLog() {
		const stored = await get<LogEntry[]>(logKey(this.#link.docId));
		if (!stored?.length) return;
		for (const entry of stored) {
			// Re-verify on load: storage is not a trust boundary, and a log written
			// by an older link must not be replayed under a rotated key.
			if (await verify(this.#link.signPub, fromBase64Url(entry.u), entry.s)) {
				this.#log.set(entry.id, entry);
				Y.applyUpdate(this.doc, fromBase64Url(entry.u), 'remote');
			}
		}
	}

	#queueSave() {
		clearTimeout(this.#saveTimer);
		this.#saveTimer = setTimeout(() => void this.#saveLog(), 500);
	}

	async #saveLog() {
		const entries = [...this.#log.values()];
		const snapshots = entries.filter((e) => e.snap);
		// Newest first while trimming, so the budget keeps recent history rather
		// than whatever happened to be at the front of the array.
		const regular: LogEntry[] = [];
		let bytes = snapshots.reduce((sum, entry) => sum + entryBytes(entry), 0);
		for (const entry of entries.filter((e) => !e.snap).reverse()) {
			if (regular.length >= KEEP_ENTRIES || bytes + entryBytes(entry) > KEEP_BYTES) break;
			bytes += entryBytes(entry);
			regular.unshift(entry);
		}
		await set(logKey(this.#link.docId), [...snapshots, ...regular]);
	}

	/** Total size of the in-memory log, for the compaction budget. */
	#logBytes(): number {
		let total = 0;
		for (const entry of this.#log.values()) total += entryBytes(entry);
		return total;
	}

	#onLocalUpdate = (update: Uint8Array, origin: unknown) => {
		// Remote updates are already in the log; re-signing them would fork history.
		if (origin === 'remote' || this.role !== 'editor' || !this.#link.signSeed) return;
		void this.#appendSigned(update, false);
	};

	async #appendSigned(update: Uint8Array, snap: boolean) {
		const seed = this.#link.signSeed;
		if (!seed) return;
		const entry: LogEntry = {
			id: toBase64Url(crypto.getRandomValues(new Uint8Array(12))),
			u: toBase64Url(update),
			s: await sign(seed, update),
			...(snap ? { snap: true } : {})
		};
		this.#log.set(entry.id, entry);
		this.#broadcast({ t: 'entries', entries: [entry] });
		this.#queueSave();
		if (!snap && (this.#log.size > SNAPSHOT_AFTER || this.#logBytes() > SNAPSHOT_AFTER_BYTES)) {
			await this.#compact();
		}
	}

	/**
	 * Collapse history into one signed snapshot.
	 *
	 * Only an editor can do this, because a snapshot is an authored update. Peers
	 * without the key keep appending until an editor next compacts — bounded by
	 * KEEP_ENTRIES on disk, so the log cannot grow without limit either way.
	 */
	async #compact() {
		const seed = this.#link.signSeed;
		if (!seed) return;
		const state = Y.encodeStateAsUpdate(this.doc);
		const entry: LogEntry = {
			id: toBase64Url(crypto.getRandomValues(new Uint8Array(12))),
			u: toBase64Url(state),
			s: await sign(seed, state),
			snap: true
		};
		this.#log.clear();
		this.#log.set(entry.id, entry);
		this.#broadcast({ t: 'entries', entries: [entry] });
		this.#queueSave();
	}

	// ---- signaling ----

	#openSocket(url: string) {
		if (this.#destroyed) return;
		const socket = new WebSocket(url);
		this.#socket = socket;

		socket.onopen = () => {
			this.#retry = 0;
			socket.send(
				JSON.stringify({ type: 'subscribe', topic: this.#link.docId, from: this.#selfId })
			);
			socket.send(
				JSON.stringify({ type: 'announce', topic: this.#link.docId, from: this.#selfId })
			);
			this.#setStatus(this.#peers.size ? 'connected' : 'waiting');
		};

		socket.onmessage = (event) => void this.#onSignal(event);

		socket.onclose = () => {
			if (this.#destroyed) return;
			this.#setStatus('connecting');
			// Exponential backoff, capped — a dropped gateway must not become a
			// reconnect storm across every open tab.
			const delay = Math.min(30_000, 500 * 2 ** this.#retry++);
			this.#retryTimer = setTimeout(() => this.#openSocket(url), delay);
		};

		socket.onerror = () => socket.close();
	}

	async #onSignal(event: MessageEvent) {
		let message: { type: string; from?: string; to?: string; signal?: unknown };
		try {
			message = JSON.parse(typeof event.data === 'string' ? event.data : '');
		} catch {
			return;
		}
		const from = message.from;
		if (!from || from === this.#selfId) return;

		if (message.type === 'announce') {
			// Deterministic initiator so two peers never both dial: lower id calls.
			if (!this.#peers.has(from)) this.#createPeer(from, this.#selfId < from);
			// Answer so the newcomer learns about peers that were already here.
			this.#socket?.send(
				JSON.stringify({
					type: 'announce-ack',
					topic: this.#link.docId,
					from: this.#selfId,
					to: from
				})
			);
		} else if (message.type === 'announce-ack' && message.to === this.#selfId) {
			if (!this.#peers.has(from)) this.#createPeer(from, this.#selfId < from);
		} else if (message.type === 'signal' && message.to === this.#selfId) {
			const peer = this.#peers.get(from) ?? this.#createPeer(from, false);
			try {
				peer.signal(message.signal as Peer.SignalData);
			} catch {
				/* malformed signal from a stale peer */
			}
		} else if (message.type === 'leave') {
			this.#peers.get(from)?.destroy();
			this.#peers.delete(from);
			this.#updatePeerCount();
		}
	}

	#createPeer(remoteId: string, initiator: boolean): Peer.Instance {
		const peer = new Peer({ initiator, trickle: true });
		this.#peers.set(remoteId, peer);

		peer.on('signal', (signal) => {
			this.#socket?.send(
				JSON.stringify({
					type: 'signal',
					topic: this.#link.docId,
					from: this.#selfId,
					to: remoteId,
					signal
				})
			);
		});
		peer.on('connect', () => {
			this.#updatePeerCount();
			void this.#send(peer, { t: 'have', ids: [...this.#log.keys()] });
			const local = this.awareness.getLocalState();
			if (local) {
				void this.#send(peer, {
					t: 'aware',
					u: toBase64Url(encodeAwarenessUpdate(this.awareness, [this.doc.clientID]))
				});
			}
		});
		peer.on('data', (data: Uint8Array) => void this.#onData(data, peer));
		peer.on('close', () => {
			this.#peers.delete(remoteId);
			this.#partials.delete(peer);
			this.#updatePeerCount();
		});
		peer.on('error', () => {
			this.#peers.delete(remoteId);
			this.#partials.delete(peer);
			this.#updatePeerCount();
		});
		return peer;
	}

	// ---- framing ----

	async #send(peer: Peer.Instance, frame: Frame) {
		if (!this.#key || !peer.connected) return;
		const bytes = new TextEncoder().encode(JSON.stringify(frame));
		const cipher = await encrypt(this.#key, bytes);

		try {
			if (cipher.length <= CHUNK_PAYLOAD) {
				const packet = new Uint8Array(1 + cipher.length);
				packet[0] = KIND_WHOLE;
				packet.set(cipher, 1);
				peer.send(packet);
				return;
			}

			const total = Math.ceil(cipher.length / CHUNK_PAYLOAD);
			if (total > MAX_CHUNKS) {
				this.onerror?.('That change is too large to share.');
				return;
			}
			const msgId = crypto.getRandomValues(new Uint32Array(1))[0];

			for (let seq = 0; seq < total; seq++) {
				const slice = cipher.subarray(seq * CHUNK_PAYLOAD, (seq + 1) * CHUNK_PAYLOAD);
				const packet = new Uint8Array(CHUNK_HEADER + slice.length);
				const view = new DataView(packet.buffer);
				packet[0] = KIND_CHUNK;
				view.setUint32(1, msgId);
				view.setUint16(5, seq);
				view.setUint16(7, total);
				packet.set(slice, CHUNK_HEADER);
				peer.send(packet);

				// Yield periodically so a large image does not monopolise the send
				// buffer and stall the connection's own keepalives.
				if (seq % 16 === 15) await new Promise((resolve) => setTimeout(resolve, 0));
				if (!peer.connected) return;
			}
		} catch {
			/* channel closed mid-send */
		}
	}

	#broadcast(frame: Frame) {
		for (const peer of this.#peers.values()) void this.#send(peer, frame);
	}

	/** Reassembles chunked frames; returns the full ciphertext or null if incomplete. */
	#reassemble(packet: Uint8Array, from: Peer.Instance): Uint8Array | null {
		if (packet[0] === KIND_WHOLE) return packet.subarray(1);
		if (packet[0] !== KIND_CHUNK || packet.length < CHUNK_HEADER) return null;

		const view = new DataView(packet.buffer, packet.byteOffset, packet.byteLength);
		const msgId = view.getUint32(1);
		const seq = view.getUint16(5);
		const total = view.getUint16(7);
		// A peer could claim any total; refuse to allocate on their word alone.
		if (total === 0 || total > MAX_CHUNKS || seq >= total) return null;

		let byPeer = this.#partials.get(from);
		if (!byPeer) this.#partials.set(from, (byPeer = new Map()));

		// Drop stale partials rather than let an abandoned transfer sit forever.
		const now = Date.now();
		for (const [id, entry] of byPeer) {
			if (now - entry.at > REASSEMBLY_TIMEOUT_MS) byPeer.delete(id);
		}

		let partial = byPeer.get(msgId);
		if (!partial) {
			partial = { chunks: new Array(total), received: 0, total, at: now };
			byPeer.set(msgId, partial);
		}
		if (partial.total !== total || partial.chunks[seq]) return null;

		partial.chunks[seq] = packet.subarray(CHUNK_HEADER);
		partial.received++;
		if (partial.received < total) return null;

		byPeer.delete(msgId);
		const size = partial.chunks.reduce((sum, chunk) => sum + (chunk?.length ?? 0), 0);
		const joined = new Uint8Array(size);
		let offset = 0;
		for (const chunk of partial.chunks) {
			if (!chunk) return null;
			joined.set(chunk, offset);
			offset += chunk.length;
		}
		return joined;
	}

	async #onData(data: Uint8Array, from: Peer.Instance) {
		if (!this.#key) return;
		const cipher = this.#reassemble(new Uint8Array(data), from);
		if (!cipher) return;
		const plain = await decrypt(this.#key, cipher);
		// A frame we cannot decrypt came from someone without the content key.
		// Drop it silently; there is nothing useful to tell the user.
		if (!plain) return;

		let frame: Frame;
		try {
			frame = JSON.parse(new TextDecoder().decode(plain));
		} catch {
			return;
		}

		if (frame.t === 'have') {
			const theirs = new Set(frame.ids);
			const missing = frame.ids.filter((id) => !this.#log.has(id));
			const offer = [...this.#log.values()].filter((entry) => !theirs.has(entry.id));
			if (missing.length) void this.#send(from, { t: 'want', ids: missing });
			if (offer.length) void this.#send(from, { t: 'entries', entries: offer });
		} else if (frame.t === 'want') {
			const wanted = frame.ids
				.map((id) => this.#log.get(id))
				.filter((entry): entry is LogEntry => !!entry);
			if (wanted.length) void this.#send(from, { t: 'entries', entries: wanted });
		} else if (frame.t === 'entries') {
			await this.#applyEntries(frame.entries);
		} else if (frame.t === 'aware') {
			// Presence is deliberately unsigned: a viewer must be able to show a
			// cursor without holding a key that would also let them edit.
			applyAwarenessUpdate(this.awareness, fromBase64Url(frame.u), 'remote');
		}
	}

	async #applyEntries(entries: LogEntry[]) {
		let applied = 0;
		for (const entry of entries) {
			if (this.#log.has(entry.id)) continue;
			const update = fromBase64Url(entry.u);
			// The security boundary. An unsigned or wrongly-signed update is dropped
			// here, in every peer, which is why a view-only link cannot write.
			if (!(await verify(this.#link.signPub, update, entry.s))) continue;
			this.#log.set(entry.id, entry);
			Y.applyUpdate(this.doc, update, 'remote');
			applied++;
		}
		if (applied) {
			this.#queueSave();
			// Relay onward so a peer that joined late is reachable through anyone.
			this.#broadcast({ t: 'entries', entries });
		}
	}

	#onAwarenessUpdate = (
		{ added, updated, removed }: { added: number[]; updated: number[]; removed: number[] },
		origin: unknown
	) => {
		if (origin === 'remote') return;
		const changed = [...added, ...updated, ...removed];
		this.#broadcast({ t: 'aware', u: toBase64Url(encodeAwarenessUpdate(this.awareness, changed)) });
	};

	#updatePeerCount() {
		this.peerCount = [...this.#peers.values()].filter((p) => p.connected).length;
		this.#setStatus(this.peerCount > 0 ? 'connected' : 'waiting');
	}

	#setStatus(status: ProviderStatus) {
		if (this.status === status) return;
		this.status = status;
		this.onstatus?.();
	}
}
